Repository TooTallNate/Java-WebSocket, pull requests merged in 2019-02, with the labels that each got.

#848 Removed unused/unrelated imports (including deprecated CORBA)
  src/test/java/org/java_websocket/exceptions/InvalidEncodingExceptionTest.java
Labels: Refactor, Test

#851 Generated changelog
  CHANGELOG.md
Labels: Documentation

#849 Fix issue #847
  src/main/java/org/java_websocket/drafts/Draft_6455.java
  src/test/java/org/java_websocket/issues/Issue847Test.java
  src/test/java/org/java_websocket/util/KeyUtils.java
Labels: Bug

#850 Fix issue #834 by starting WebSocketWorker of the WebSocketServer in the start function
  src/main/java/org/java_websocket/server/WebSocketServer.java
  src/test/java/org/java_websocket/issues/AllIssueTests.java
  src/test/java/org/java_websocket/issues/Issue834Test.java
Labels: Bug, Server

#856 Move the startup of the WebSocketWorker inside of run()
  src/main/java/org/java_websocket/server/WebSocketServer.java
  src/test/java/org/java_websocket/issues/Issue855Test.java
Labels: Bug, Server

#858 Update documentation for 1.4.0
  .github/ISSUE_TEMPLATE/bug_report.md
  README.markdown
  src/main/example/simplelogger.properties
Labels: Documentation

#860 Release of 1.4.0
  CHANGELOG.md
  README.markdown
  build.gradle
  pom.xml
Labels: Documentation
