Repository TooTallNate/Java-WebSocket, pull requests merged in 2020-05, with the labels that each got.

#1009 Update CHANGELOG.md
  CHANGELOG.md
Labels: Documentation

#1010 Release of 1.5.0
  README.markdown
  pom.xml
Labels: Documentation

#1014 Move setEndpointIdentificationAlgorithm inside onSetSSLParametersof
  src/main/java/org/java_websocket/client/WebSocketClient.java
  src/test/java/org/java_websocket/issues/Issue997Test.java
Labels: Android, Bug

#1015 Update CHANGELOG.md
  CHANGELOG.md
Labels: Documentation

#1016 Release 1.5.1
  README.markdown
  pom.xml
Labels: Documentation

#1018 Added missing return character
  src/main/java/org/java_websocket/WebSocketImpl.java
Labels: Bug, Client, Server
